### ISSUE TITLE
Web Token not generated/deleted correctly

### ISSUE THREAD

**Issue by asim** [m3o/cloud#108]
The issues

- Web tokens are not deleted on logout
- Web token cookies "micro_api_token" are not deleted on logout
- Web tokens appear not to be regenerated because of this issue
- Multiple web tokens exist in the UI of the same name (differentiate per device)

**Comment by crufter** [comment]
Fixed by #110 except this
> Multiple web tokens exist in the UI of the same name (differentiate per device)

**Comment by crufter** [comment]
More fixes to this in #125
